---
title: "HW2"
output: github_document
---

#Problem 1
```{r}
library(tidyverse)
subway_file=
  read_csv(file="./NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(-division,-exit_only,-staff_hours,-staffing) %>%
  mutate(entry=recode(entry,"YES"=T,"NO"=F))
dim(subway_file)  

#The dataset contains lines, station names, station latitude, station longitude, routes, entrance type, entry, vending, ADA, ADA notes, and the dimension is 1868x28 #

#Use distinct function, we can get there are totally 465 distinct stations#
distinct(subway_file,line,station_name) 


#Therefore, there are 468 stations are ADA compliant#
sum(subway_file$ada)     


#Convert the value in vending column into 0 and 1 from Yes and No, then we get 183 stations without vending. Using 183 diveded by total station number 1868, then we can get the proportion of station without vending#
new_list=ifelse(subway_file$vending=="YES", 0, 1)
sum(new_list)/1868

#We change the file into tidy, and we can get there are 60 stations containing A#
real_data=gather(subway_file,key=route,value=bus_number,route1 :route11)
after_data=distinct(real_data,line,station_name,route,bus_number,ada) 
after_data
length(which(after_data$bus_number == "A")) 
#And 925 stations are ADA compliant#
sum(after_data$ada)
```
#Problem 2
```{r second}
library(tidyverse)
library(readxl)
data_file=
  read_excel("./HealthyHarborWaterWheelTotals2017-9-26.xlsx")  %>%
  janitor::clean_names() %>%
  select(-x_1)                    #x_1 represents the columns containing notes, and I remove this column#
data_file

#Then I omit rows without value in Dumpster column, and now there are 216 rows left# 
new_file=data_file[!(data_file$dumpster == "" | is.na(data_file$dumpster)), ]
new_file
#Then I round the number of sport balls to integer 3287.6 to 3288#
as.integer(round(new_file$sports_balls))

#Then I read and create new variables while year=2016,2017, and adding a new variable year# 
new_data_2016=read_excel("./HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2016 Precipitation")%>%
  janitor::clean_names()%>%
  mutate(year=2016)
new_data_2016

data_file_2017=read_excel("./HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2017 Precipitation")%>%
  janitor::clean_names()%>%
  mutate(year=2017)

#remove the missing values#
new_data_2017 <- na.omit(data_file_2017)
new_data_2017

#Then combine the two datas#
new_data=bind_rows(new_data_2016,new_data_2017)
new_data
month.name[new_data$month]

#In 2016, there are 12 months precipitation observations, while in 2017, there are 8 observations.#
#In 2017, the total precipitaion is 29.93. And the median of 2016 sport balls is 26.#
sum(new_data_2017$total)
new_file_2016=filter(new_file,year==2016)
median(new_file_2016$sports_balls)
```

#Problem 3
```{r third}
library(tidyverse)
library(p8105.datasets)

#load and run the file from git#
gitfile=brfss_smart2010                            
gitfile

#remove several specific columns, and there are 5 columns left now#
new=select(gitfile,-Class,-Topic,-Question,-Sample_Size,-Confidence_limit_Low:-GeoLocation)
new

#Then I change the value of response (excellent to poor) into columns using "spread" function and get the propotion#
head=head(new,5)
proportion=spread(head,key=Response,value=Data_value)
proportion










```
